//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPMailerService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailData", Namespace="http://schemas.datacontract.org/2004/07/Teleperformance.TPMailer")]
    public partial class MailData : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TPMailerService.AttachmentFile[] AttachmentsField;
        
        private string BCCAddressField;
        
        private string CCAddressField;
        
        private string FromAddressField;
        
        private bool IsHTMLBodyField;
        
        private string MailBodyField;
        
        private string MailSubjectField;
        
        private string ToAddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TPMailerService.AttachmentFile[] Attachments
        {
            get
            {
                return this.AttachmentsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AttachmentsField, value) != true))
                {
                    this.AttachmentsField = value;
                    this.RaisePropertyChanged("Attachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BCCAddress
        {
            get
            {
                return this.BCCAddressField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BCCAddressField, value) != true))
                {
                    this.BCCAddressField = value;
                    this.RaisePropertyChanged("BCCAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CCAddress
        {
            get
            {
                return this.CCAddressField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CCAddressField, value) != true))
                {
                    this.CCAddressField = value;
                    this.RaisePropertyChanged("CCAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromAddress
        {
            get
            {
                return this.FromAddressField;
            }
            set
            {
                if ((object.ReferenceEquals(this.FromAddressField, value) != true))
                {
                    this.FromAddressField = value;
                    this.RaisePropertyChanged("FromAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHTMLBody
        {
            get
            {
                return this.IsHTMLBodyField;
            }
            set
            {
                if ((this.IsHTMLBodyField.Equals(value) != true))
                {
                    this.IsHTMLBodyField = value;
                    this.RaisePropertyChanged("IsHTMLBody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailBody
        {
            get
            {
                return this.MailBodyField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MailBodyField, value) != true))
                {
                    this.MailBodyField = value;
                    this.RaisePropertyChanged("MailBody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailSubject
        {
            get
            {
                return this.MailSubjectField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MailSubjectField, value) != true))
                {
                    this.MailSubjectField = value;
                    this.RaisePropertyChanged("MailSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToAddress
        {
            get
            {
                return this.ToAddressField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ToAddressField, value) != true))
                {
                    this.ToAddressField = value;
                    this.RaisePropertyChanged("ToAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachmentFile", Namespace="http://schemas.datacontract.org/2004/07/Teleperformance.TPMailer")]
    public partial class AttachmentFile : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string AttachmentFileNameField;
        
        private string AttachmentMIMETypeField;
        
        private System.IO.MemoryStream AttachmentMemoryStreamField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttachmentFileName
        {
            get
            {
                return this.AttachmentFileNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AttachmentFileNameField, value) != true))
                {
                    this.AttachmentFileNameField = value;
                    this.RaisePropertyChanged("AttachmentFileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttachmentMIMEType
        {
            get
            {
                return this.AttachmentMIMETypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AttachmentMIMETypeField, value) != true))
                {
                    this.AttachmentMIMETypeField = value;
                    this.RaisePropertyChanged("AttachmentMIMEType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.IO.MemoryStream AttachmentMemoryStream
        {
            get
            {
                return this.AttachmentMemoryStreamField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AttachmentMemoryStreamField, value) != true))
                {
                    this.AttachmentMemoryStreamField = value;
                    this.RaisePropertyChanged("AttachmentMemoryStream");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TPMailerService.IMail")]
    public interface IMail
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/SendMail", ReplyAction="http://tempuri.org/IMail/SendMailResponse")]
        void SendMail(TPMailerService.MailData mailData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/SendMail", ReplyAction="http://tempuri.org/IMail/SendMailResponse")]
        System.Threading.Tasks.Task SendMailAsync(TPMailerService.MailData mailData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/SendMailWithAttachment", ReplyAction="http://tempuri.org/IMail/SendMailWithAttachmentResponse")]
        void SendMailWithAttachment(TPMailerService.MailData mailData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/SendMailWithAttachment", ReplyAction="http://tempuri.org/IMail/SendMailWithAttachmentResponse")]
        System.Threading.Tasks.Task SendMailWithAttachmentAsync(TPMailerService.MailData mailData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IMailChannel : TPMailerService.IMail, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class MailClient : System.ServiceModel.ClientBase<TPMailerService.IMail>, TPMailerService.IMail
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MailClient(EndpointConfiguration endpointConfiguration) : 
                base(MailClient.GetBindingForEndpoint(endpointConfiguration), MailClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MailClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MailClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void SendMail(TPMailerService.MailData mailData)
        {
            base.Channel.SendMail(mailData);
        }
        
        public System.Threading.Tasks.Task SendMailAsync(TPMailerService.MailData mailData)
        {
            return base.Channel.SendMailAsync(mailData);
        }
        
        public void SendMailWithAttachment(TPMailerService.MailData mailData)
        {
            base.Channel.SendMailWithAttachment(mailData);
        }
        
        public System.Threading.Tasks.Task SendMailWithAttachmentAsync(TPMailerService.MailData mailData)
        {
            return base.Channel.SendMailWithAttachmentAsync(mailData);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IMail))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.None;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IMail))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IMail))
            {
                return new System.ServiceModel.EndpointAddress("https://bkr-web01-b.teleperformanceusa.com/Teleperformance/TPMailer/Mail.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IMail))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://utilities.teleperformanceusa.com:5025/Teleperformance/TPMailer/Mail.svc" +
                        "");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSHttpBinding_IMail,
            
            NetTcpBinding_IMail,
        }
    }
}
